In [1]:
# datetime module

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('tv_shows.csv')

In [5]:
data.columns

Index(['Unnamed: 0', 'ID', 'Title', 'Year', 'Age', 'IMDb', 'Rotten Tomatoes',
       'Netflix', 'Hulu', 'Prime Video', 'Disney+', 'Type'],
      dtype='object')

In [9]:
df=data[['Title', 'Year', 'IMDb',
       'Netflix', 'Hulu', 'Prime Video', 'Disney+']]

In [11]:
len(df)

5368

In [13]:
d=df[:100]

In [14]:
d

,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+
0,Breaking Bad,2008,9.4/10,1,0,0,0
1,Stranger Things,2016,8.7/10,1,0,0,0
2,Attack on Titan,2013,9.0/10,1,1,0,0
3,Better Call Saul,2015,8.8/10,1,0,0,0
4,Dark,2017,8.8/10,1,0,0,0
...,...,...,...,...,...,...,...
95,Halt and Catch Fire,2014,8.4/10,1,0,0,0
96,Monty Python's Flying Circus,1969,8.8/10,1,0,0,0
97,After Life,2019,8.4/10,1,0,0,0
98,Riverdale,2017,6.8/10,1,1,0,0
99,Big Mouth,2017,7.9/10,1,0,0,0

In [30]:
dates=pd.date_range('20211201','20220120')

In [31]:
dates

DatetimeIndex(['2021-12-01', '2021-12-02', '2021-12-03', '2021-12-04',
               '2021-12-05', '2021-12-06', '2021-12-07', '2021-12-08',
               '2021-12-09', '2021-12-10', '2021-12-11', '2021-12-12',
               '2021-12-13', '2021-12-14', '2021-12-15', '2021-12-16',
               '2021-12-17', '2021-12-18', '2021-12-19', '2021-12-20',
               '2021-12-21', '2021-12-22', '2021-12-23', '2021-12-24',
               '2021-12-25', '2021-12-26', '2021-12-27', '2021-12-28',
               '2021-12-29', '2021-12-30', '2021-12-31', '2022-01-01',
               '2022-01-02', '2022-01-03', '2022-01-04', '2022-01-05',
               '2022-01-06', '2022-01-07', '2022-01-08', '2022-01-09',
               '2022-01-10', '2022-01-11', '2022-01-12', '2022-01-13',
               '2022-01-14', '2022-01-15', '2022-01-16', '2022-01-17',
               '2022-01-18', '2022-01-19', '2022-01-20'],
              dtype='datetime64[ns]', freq='D')

In [64]:
date=pd.date_range('20200301',periods=100)

In [65]:
date

DatetimeIndex(['2020-03-01', '2020-03-02', '2020-03-03', '2020-03-04',
               '2020-03-05', '2020-03-06', '2020-03-07', '2020-03-08',
               '2020-03-09', '2020-03-10', '2020-03-11', '2020-03-12',
               '2020-03-13', '2020-03-14', '2020-03-15', '2020-03-16',
               '2020-03-17', '2020-03-18', '2020-03-19', '2020-03-20',
               '2020-03-21', '2020-03-22', '2020-03-23', '2020-03-24',
               '2020-03-25', '2020-03-26', '2020-03-27', '2020-03-28',
               '2020-03-29', '2020-03-30', '2020-03-31', '2020-04-01',
               '2020-04-02', '2020-04-03', '2020-04-04', '2020-04-05',
               '2020-04-06', '2020-04-07', '2020-04-08', '2020-04-09',
               '2020-04-10', '2020-04-11', '2020-04-12', '2020-04-13',
               '2020-04-14', '2020-04-15', '2020-04-16', '2020-04-17',
               '2020-04-18', '2020-04-19', '2020-04-20', '2020-04-21',
               '2020-04-22', '2020-04-23', '2020-04-24', '2020-04-25',
               '2020-04-26', '2020-04-27', '2020-04-28', '2020-04-29',
               '2020-04-30', '2020-05-01', '2020-05-02', '2020-05-03',
               '2020-05-04', '2020-05-05', '2020-05-06', '2020-05-07',
               '2020-05-08', '2020-05-09', '2020-05-10', '2020-05-11',
               '2020-05-12', '2020-05-13', '2020-05-14', '2020-05-15',
               '2020-05-16', '2020-05-17', '2020-05-18', '2020-05-19',
               '2020-05-20', '2020-05-21', '2020-05-22', '2020-05-23',
               '2020-05-24', '2020-05-25', '2020-05-26', '2020-05-27',
               '2020-05-28', '2020-05-29', '2020-05-30', '2020-05-31',
               '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04',
               '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08'],
              dtype='datetime64[ns]', freq='D')

In [66]:
d.index=date

In [55]:
d

,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+
2020-01-01,Breaking Bad,2008,9.4/10,1,0,0,0
2020-01-02,Stranger Things,2016,8.7/10,1,0,0,0
2020-01-03,Attack on Titan,2013,9.0/10,1,1,0,0
2020-01-04,Better Call Saul,2015,8.8/10,1,0,0,0
2020-01-05,Dark,2017,8.8/10,1,0,0,0
...,...,...,...,...,...,...,...
2020-04-05,Halt and Catch Fire,2014,8.4/10,1,0,0,0
2020-04-06,Monty Python's Flying Circus,1969,8.8/10,1,0,0,0
2020-04-07,After Life,2019,8.4/10,1,0,0,0
2020-04-08,Riverdale,2017,6.8/10,1,1,0,0
2020-04-09,Big Mouth,2017,7.9/10,1,0,0,0

In [58]:
d.loc['2020-03-10']

Title          How to Get Away with Murder
Year                                  2014
IMDb                                8.1/10
Netflix                                  1
Hulu                                     1
Prime Video                              0
Disney+                                  0
Name: 2020-03-10 00:00:00, dtype: object

In [59]:
d['2020-01-01':'2020-01-15']

,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+
2020-01-01,Breaking Bad,2008,9.4/10,1,0,0,0
2020-01-02,Stranger Things,2016,8.7/10,1,0,0,0
2020-01-03,Attack on Titan,2013,9.0/10,1,1,0,0
2020-01-04,Better Call Saul,2015,8.8/10,1,0,0,0
2020-01-05,Dark,2017,8.8/10,1,0,0,0
2020-01-06,Avatar: The Last Airbender,2005,9.3/10,1,0,1,0
2020-01-07,Peaky Blinders,2013,8.8/10,1,0,0,0
2020-01-08,The Walking Dead,2010,8.2/10,1,0,0,0
2020-01-09,Black Mirror,2011,8.8/10,1,0,0,0
2020-01-10,The Queen's Gambit,2020,8.6/10,1,0,0,0
2020-01-11,Mindhunter,2017,8.6/10,1,0,0,0
2020-01-12,Community,2009,8.5/10,1,1,1,0
2020-01-13,Narcos,2015,8.8/10,1,0,0,0
2020-01-14,Shameless,2011,8.5/10,1,1,1,0
2020-01-15,Money Heist,2017,8.3/10,1,0,0,0

In [67]:
d['date']=date

c:\users\rmani\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [68]:
d

,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+,date,dayofyear
2020-03-01,Breaking Bad,2008,9.4/10,1,0,0,0,2020-03-01,1
2020-03-02,Stranger Things,2016,8.7/10,1,0,0,0,2020-03-02,2
2020-03-03,Attack on Titan,2013,9.0/10,1,1,0,0,2020-03-03,3
2020-03-04,Better Call Saul,2015,8.8/10,1,0,0,0,2020-03-04,4
2020-03-05,Dark,2017,8.8/10,1,0,0,0,2020-03-05,5
...,...,...,...,...,...,...,...,...,...
2020-06-04,Halt and Catch Fire,2014,8.4/10,1,0,0,0,2020-06-04,96
2020-06-05,Monty Python's Flying Circus,1969,8.8/10,1,0,0,0,2020-06-05,97
2020-06-06,After Life,2019,8.4/10,1,0,0,0,2020-06-06,98
2020-06-07,Riverdale,2017,6.8/10,1,1,0,0,2020-06-07,99
2020-06-08,Big Mouth,2017,7.9/10,1,0,0,0,2020-06-08,100

In [69]:
d['dayofyear']=d['date'].dt.dayofyear

c:\users\rmani\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [70]:
d

,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+,date,dayofyear
2020-03-01,Breaking Bad,2008,9.4/10,1,0,0,0,2020-03-01,61
2020-03-02,Stranger Things,2016,8.7/10,1,0,0,0,2020-03-02,62
2020-03-03,Attack on Titan,2013,9.0/10,1,1,0,0,2020-03-03,63
2020-03-04,Better Call Saul,2015,8.8/10,1,0,0,0,2020-03-04,64
2020-03-05,Dark,2017,8.8/10,1,0,0,0,2020-03-05,65
...,...,...,...,...,...,...,...,...,...
2020-06-04,Halt and Catch Fire,2014,8.4/10,1,0,0,0,2020-06-04,156
2020-06-05,Monty Python's Flying Circus,1969,8.8/10,1,0,0,0,2020-06-05,157
2020-06-06,After Life,2019,8.4/10,1,0,0,0,2020-06-06,158
2020-06-07,Riverdale,2017,6.8/10,1,1,0,0,2020-06-07,159
2020-06-08,Big Mouth,2017,7.9/10,1,0,0,0,2020-06-08,160

In [91]:
d['month']=d['date'].dt.day_name()

c:\users\rmani\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [98]:
d.drop('month',inplace=True,axis=1)

In [102]:
d['day_name']=d['date'].dt.day_name()

c:\users\rmani\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [103]:
d

,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+,date,day_name
2020-03-01,Breaking Bad,2008,9.4/10,1,0,0,0,2020-03-01,Sunday
2020-03-02,Stranger Things,2016,8.7/10,1,0,0,0,2020-03-02,Monday
2020-03-03,Attack on Titan,2013,9.0/10,1,1,0,0,2020-03-03,Tuesday
2020-03-04,Better Call Saul,2015,8.8/10,1,0,0,0,2020-03-04,Wednesday
2020-03-05,Dark,2017,8.8/10,1,0,0,0,2020-03-05,Thursday
...,...,...,...,...,...,...,...,...,...
2020-06-04,Halt and Catch Fire,2014,8.4/10,1,0,0,0,2020-06-04,Thursday
2020-06-05,Monty Python's Flying Circus,1969,8.8/10,1,0,0,0,2020-06-05,Friday
2020-06-06,After Life,2019,8.4/10,1,0,0,0,2020-06-06,Saturday
2020-06-07,Riverdale,2017,6.8/10,1,1,0,0,2020-06-07,Sunday
2020-06-08,Big Mouth,2017,7.9/10,1,0,0,0,2020-06-08,Monday

In [108]:
d['dayofmonth']=d['date'].dt.day
#  day ====? month day
# month===> month number
# day_name===> weekdayname
# dayofyear ---> day of year

c:\users\rmani\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [111]:
d[:35]

,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+,date,day_name,dayofmonth
2020-03-01,Breaking Bad,2008,9.4/10,1,0,0,0,2020-03-01,Sunday,1
2020-03-02,Stranger Things,2016,8.7/10,1,0,0,0,2020-03-02,Monday,2
2020-03-03,Attack on Titan,2013,9.0/10,1,1,0,0,2020-03-03,Tuesday,3
2020-03-04,Better Call Saul,2015,8.8/10,1,0,0,0,2020-03-04,Wednesday,4
2020-03-05,Dark,2017,8.8/10,1,0,0,0,2020-03-05,Thursday,5
2020-03-06,Avatar: The Last Airbender,2005,9.3/10,1,0,1,0,2020-03-06,Friday,6
2020-03-07,Peaky Blinders,2013,8.8/10,1,0,0,0,2020-03-07,Saturday,7
2020-03-08,The Walking Dead,2010,8.2/10,1,0,0,0,2020-03-08,Sunday,8
2020-03-09,Black Mirror,2011,8.8/10,1,0,0,0,2020-03-09,Monday,9
2020-03-10,The Queen's Gambit,2020,8.6/10,1,0,0,0,2020-03-10,Tuesday,10
2020-03-11,Mindhunter,2017,8.6/10,1,0,0,0,2020-03-11,Wednesday,11
2020-03-12,Community,2009,8.5/10,1,1,1,0,2020-03-12,Thursday,12
2020-03-13,Narcos,2015,8.8/10,1,0,0,0,2020-03-13,Friday,13
2020-03-14,Shameless,2011,8.5/10,1,1,1,0,2020-03-14,Saturday,14
2020-03-15,Money Heist,2017,8.3/10,1,0,0,0,2020-03-15,Sunday,15
2020-03-16,Marvel's Daredevil,2015,8.6/10,1,0,0,0,2020-03-16,Monday,16
2020-03-17,Lucifer,2016,8.1/10,1,0,0,0,2020-03-17,Tuesday,17
2020-03-18,Supernatural,2005,8.4/10,1,0,0,0,2020-03-18,Wednesday,18
2020-03-19,The Witcher,2019,8.2/10,1,0,0,0,2020-03-19,Thursday,19
2020-03-20,Ozark,2017,8.4/10,1,0,0,0,2020-03-20,Friday,20
2020-03-21,The Crown,2016,8.6/10,1,0,0,0,2020-03-21,Saturday,21
2020-03-22,Cobra Kai,2018,8.6/10,1,0,0,0,2020-03-22,Sunday,22
2020-03-23,The Blacklist,2013,8.0/10,1,0,0,0,2020-03-23,Monday,23
2020-03-24,The Flash,2014,7.6/10,1,0,0,0,2020-03-24,Tuesday,24
2020-03-25,Outlander,2014,8.4/10,1,0,0,0,2020-03-25,Wednesday,25
2020-03-26,Fullmetal Alchemist: Brotherhood,2009,9.1/10,1,1,0,0,2020-03-26,Thursday,26
2020-03-27,The Good Place,2016,8.2/10,1,0,0,0,2020-03-27,Friday,27
2020-03-28,House of Cards,2013,8.7/10,1,0,0,0,2020-03-28,Saturday,28
2020-03-29,Atypical,2017,8.3/10,1,0,0,0,2020-03-29,Sunday,29
2020-03-30,Grey's Anatomy,2005,7.5/10,1,1,0,0,2020-03-30,Monday,30
2020-03-31,Arrested Development,2003,8.7/10,1,1,0,0,2020-03-31,Tuesday,31
2020-04-01,Lupin,2021,7.5/10,1,0,0,0,2020-04-01,Wednesday,1
2020-04-02,The Umbrella Academy,2019,8.0/10,1,0,0,0,2020-04-02,Thursday,2
2020-04-03,Orange Is the New Black,2013,8.0/10,1,0,0,0,2020-04-03,Friday,3
2020-04-04,The Vampire Diaries,2009,7.7/10,1,0,0,0,2020-04-04,Saturday,4

In [112]:
d['dayofweek']=d['date'].dt.weekday

c:\users\rmani\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [126]:
d[(d['day_name']!='Sunday')]

,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+,date,day_name,dayofmonth,dayofweek
2020-03-02,Stranger Things,2016,8.7/10,1,0,0,0,2020-03-02,Monday,2,0
2020-03-03,Attack on Titan,2013,9.0/10,1,1,0,0,2020-03-03,Tuesday,3,1
2020-03-04,Better Call Saul,2015,8.8/10,1,0,0,0,2020-03-04,Wednesday,4,2
2020-03-05,Dark,2017,8.8/10,1,0,0,0,2020-03-05,Thursday,5,3
2020-03-06,Avatar: The Last Airbender,2005,9.3/10,1,0,1,0,2020-03-06,Friday,6,4
...,...,...,...,...,...,...,...,...,...,...,...
2020-06-03,Manifest,2018,7.2/10,1,1,0,0,2020-06-03,Wednesday,3,2
2020-06-04,Halt and Catch Fire,2014,8.4/10,1,0,0,0,2020-06-04,Thursday,4,3
2020-06-05,Monty Python's Flying Circus,1969,8.8/10,1,0,0,0,2020-06-05,Friday,5,4
2020-06-06,After Life,2019,8.4/10,1,0,0,0,2020-06-06,Saturday,6,5
2020-06-08,Big Mouth,2017,7.9/10,1,0,0,0,2020-06-08,Monday,8,0

# SQL

In [128]:
nums=lambda x: x**2

In [129]:
# lambda argumnet : expression

In [130]:
nums(10)

100

In [131]:
num=lambda x,y: x+y

In [132]:
num(10,20)

30

In [133]:

num(30,60)

90

In [134]:
num

In [135]:
d=lambda a: 'even' if a%2==0 else 'odd'

In [136]:
d(22)

'even'

In [137]:
d(12)

'even'

In [138]:
d(11)

'odd'